### ISSUE TITLE
What kind of paid RPC node should I use?

### ISSUE THREAD

**Issue by SuarezCN** [AL-THE-BOT-FATHER/raydium_py#6]
I purchased the Helius developer plan, but the code still runs with an error: 
**Error fetching pool keys: 'NoneType' object has no attribute 'data'.**
More specifically, the exception occurs in this line of code:
**client.get_account_info_json_parsed(marketId, commitment=Processed).value.data**
The data obtained does not have a value attribute
Thanks for your answer

**Comment by AL-THE-BOT-FATHER** [comment]
Post the mint address you're trying to buy.

**Comment by tonyfa** [comment]
I don't think your code works. I just cloned and have a paid node from Chainstack.

Issue 1 
I get the same error as Suarez - if I change the token_address in the config.py file to anything other than POPCAT 
I tried 
Render rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof 
and 
USDC EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v)
**Error fetching pool keys: 'NoneType' object has no attribute 'data'**

Issue 2
If I leave the token as POPCAT and have POPCAT in my wallet. 
I tried to execute example_buy.py or example_sell.py the program successfully ran and I got a Transaction Signature but the program keeps on retrying the confirmation and the transaction is not on solscan

here is 2 tx signatures I just got back - one sell and one buy
467iFJeWpcSuBtGfG1xtTP2DyAkpGF4eA6KKdRLnwaGeKUKQb7gjpJHoFGP1Yfm6PZQfCeXMt3ZGciWB2BeadKpE
3tVETs86qS8UJCpShsffwSXviZWt5hsR7aaTJeQUedF4VVUtqvNaGyE33eAKeLmPrak8WarNNQoGFKz2PEqEGe79

I tried this 6 times 3 buys and 3 sells none created

**Comment by AL-THE-BOT-FATHER** [comment]
1. You don't put the token in the config.py. That is where you put your private key and RPC url. This is clearly stated.
2. If you actually read the FAQ I clearly state that this only does SOL pairs not USDC.
3. If there is no txn signature on solscan that is the quality of your RPC, not the code. If there is a txn signature and a failed transaction then that's the code.

Please read the FAQ before using any GitHub repo.

**Comment by AL-THE-BOT-FATHER** [comment]
![Screenshot_20241207_042339_DEX Screener](https://github.com/user-attachments/assets/65c1c5ab-0f27-41e3-922a-860fdfcdba1e)

This is a scam token.

**Comment by tonyfa** [comment]
That is not a scam token address - https://solscan.io/token/rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof

I update the token_address in example_buy.py or example_sell.py. 

Can you run your program with a token other than POPCAT?

So, if I try Ray instead, I get the same error. 
https://solscan.io/token/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R

Getting pair address from API...
Starting buy transaction for pair address: 2AXXcN6oN9bBT5owwmTH53C7QHUXvhLeu718Kqt8rvY2
Fetching pool keys...
Error fetching pool keys: 'NoneType' object has no attribute 'data'
No pool keys found...

**Comment by AL-THE-BOT-FATHER** [comment]
That's because it a CLMM pool. This repo only works for AMM pools. Use a different repo.

**Comment by tonyfa** [comment]
Thanks for the reply. 

Maybe you could add this to the README

"Error fetching pool keys: 'NoneType' object has no attribute 'data'" 
Answer: This repo only works for AMM pools and not CLMM pool
