### ISSUE TITLE
get_pair_address

### ISSUE THREAD

**Issue by HowHsu** [AL-THE-BOT-FATHER/raydium_py#7]
The get_pair_address() calls the raydium api v3 but defaultly picks up the first pool, that may cause error, since for some tokens, like ORCA, the returned pair is (ORCA, RAY), not (ORCA, WSOL). 
A alternative way is deliver 'mint1=ORCA&mint2=WSOL', but that's not good for  low liquidity (WSOL, some token) pairs.
So a good way would be support a router to find a link from WSOL to the target token.
Any chance to support it?

**Comment by AL-THE-BOT-FATHER** [comment]
This repo does support Orca pools. 

Can you give me the mint you are having issues with?

**Comment by HowHsu** [comment]
> This repo does support Orca pools.
> 
> Can you give me the mint you are having issues with?

ORCA itself，what I mean is the mint I deliver is ORCA token...

**Comment by HowHsu** [comment]
`curl "https://api-v3.raydium.io/pools/info/mint?mint1=orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE&poolType=all&poolSortField=liquidity&sortType=desc&pageSize=1&page=1"`
You can run this(this is the code in your utils.py), the pair returns is (ORCA, RAY)， not (ORCA, WSOL)

**Comment by AL-THE-BOT-FATHER** [comment]
This repo only supports AMM pools, not CLMM or CPMM.

I see what you mean for the multiple pools though.

**Comment by HowHsu** [comment]
> This repo only supports AMM pools, not CLMM or CPMM.
> 
> I see what you mean for the multiple pools though.

Sorry I'm really new to learning the Solana ecosystem, do you mean that the pool returned is not AMM pool? Any suggestions on how to address this issue?

**Comment by AL-THE-BOT-FATHER** [comment]
Use my Jupiter repo.

**Comment by HowHsu** [comment]
> Use my Jupiter repo.

Super thanks, AL. This is really helpful for me. By the way, any plans to do  python project for aggregate swap on EVM chains
